"""Export an Account Action Plan to a clean, branded PDF (downloadable from the app/CLI).

Pure: build_account_pdf(intel) -> bytes. Uses fpdf2 core fonts (no system deps, works on
Streamlit Cloud); text is sanitized to latin-1 so LLM unicode never breaks the render.
"""
from __future__ import annotations

from fpdf import FPDF

from .crm import build_action_package
from .models import AccountIntel

GREEN = (0, 204, 68)
DARK = (20, 22, 26)
MUTED = (110, 116, 126)

# Map common LLM unicode to ASCII (built via chr() so this source stays plain-ASCII).
_REPL = {
    chr(0x2014): "-", chr(0x2013): "-", chr(0x2192): "->", chr(0x2022): "-", chr(0x2026): "...",
    chr(0x201C): '"', chr(0x201D): '"', chr(0x2018): "'", chr(0x2019): "'", chr(0x00D7): "x", chr(0x2122): "(TM)",
}


def _safe(text: str) -> str:
    for k, v in _REPL.items():
        text = text.replace(k, v)
    return text.encode("latin-1", "ignore").decode("latin-1")


class _PDF(FPDF):
    def header(self) -> None:
        self.set_fill_color(*GREEN)
        self.rect(0, 0, 210, 16, "F")
        self.set_xy(12, 4)
        self.set_font("helvetica", "B", 13)
        self.set_text_color(8, 20, 10)
        self.cell(0, 8, "MARKSTER RECON  -  Account Action Plan")
        self.ln(16)
        self.set_text_color(*DARK)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("helvetica", "", 7)
        self.set_text_color(*MUTED)
        self.cell(0, 6, _safe("Sourced via 6 Bright Data products - Azure GPT-5.5 - provenance on every signal - "
                              "deterministic confidence. Generated by Markster Recon."), align="C")


def _heading(pdf: _PDF, text: str) -> None:
    pdf.ln(2)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(*GREEN)
    pdf.cell(0, 6, _safe(text), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*DARK)


def _body(pdf: _PDF, text: str, size: int = 10) -> None:
    pdf.set_font("helvetica", "", size)
    pdf.multi_cell(0, 5, _safe(text), new_x="LMARGIN", new_y="NEXT")


def build_account_pdf(intel: AccountIntel) -> bytes:
    pkg = build_action_package(intel)
    pdf = _PDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.set_margins(12, 18, 12)
    pdf.add_page()

    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 9, _safe(intel.company), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 5, _safe(f"Confidence {intel.confidence:.0%} (coverage x signal strength)  |  "
                         f"LLM: {intel.llm_used}  |  {len(intel.signals)} signals  |  generated {intel.generated_at[:16]}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*DARK)
    if intel.one_liner:
        pdf.ln(1)
        pdf.set_font("helvetica", "B", 11)
        pdf.multi_cell(0, 5, _safe(intel.one_liner), new_x="LMARGIN", new_y="NEXT")

    _heading(pdf, "The read - why this account, why now")
    _body(pdf, intel.the_read or "-")
    if intel.terrain:
        _heading(pdf, "Terrain")
        _body(pdf, intel.terrain)
    if intel.routes:
        _heading(pdf, "Routes to enter")
        for r in intel.routes:
            _body(pdf, f"- {r}")
    if intel.who_decides:
        _heading(pdf, "Who shapes the decision")
        for w in intel.who_decides:
            _body(pdf, f"- {w}")

    _heading(pdf, f"Live signals ({len(intel.signals)}) - each with its source")
    for s in intel.signals:
        pdf.set_font("helvetica", "B", 9)
        pdf.multi_cell(0, 5, _safe(f"[{s.category}] ({s.confidence:.0%})  {s.summary}"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 8)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(0, 4, _safe(f"source: {s.provenance.source_url}  ({s.provenance.method})"),
                       new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*DARK)

    if intel.evidence_gaps:
        _heading(pdf, "Evidence gaps - verify before acting")
        for g in intel.evidence_gaps:
            _body(pdf, f"- {g}")

    _heading(pdf, "Next actions - most urgent first")
    for i, a in enumerate(intel.next_actions, 1):
        _body(pdf, f"{i}. {a}")

    _heading(pdf, "Agentic CRM action (what Recon writes to your CRM)")
    if pkg.caveat:
        pdf.set_text_color(180, 120, 0)
        _body(pdf, f"NOTE: {pkg.caveat}")
        pdf.set_text_color(*DARK)
    _body(pdf, f"Task [{pkg.task.priority}]: {pkg.task.subject}  (suggested due {pkg.task.due_date})")

    return bytes(pdf.output())
